name: Feature
description: Suggest a new feature.
labels:
  - 'enhancement'
body:
  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
    validations:
      required: true

  - type: textarea
    id: attempted-solutions
    attributes:
      label: Attempted Solutions
    validations:
      required: false