name: Publish Python 🐍 distributions 📦 to PyPI seqslabcli

on:
  release:
    types: [ released ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine

      - name: Build dist
        run: python setup.py sdist bdist_wheel --python-tag py3

      - name: Archive dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist/*.tar.gz
            dist/*.whl

      - name: Verify long description rendering
        run: twine check dist/*


      - name: Publish distribution 📦 to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload --non-interactive -u __token__ -p "${PYPI_API_TOKEN}" dist/*