name: seqslab connector staging
on:
  workflow_dispatch:
    inputs:
      draftRelease:
        description: 'Create Draft Release ?'
        required: true
        default: 'Yes'

jobs:
  test-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Get versioning information
        id: versions
        run: |
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          CURRENT_VERSION=$(cat seqslab/__init__.py | grep "__version__"| awk '{print $3}' | sed 's/^"//'| sed 's/"$//' )
          
          # set output
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Print versioning information
        run: |
          echo "Print CURRENT_VERSION"
          echo ${{ steps.versions.outputs.CURRENT_VERSION }}

      - uses: mukunku/tag-exists-action@v1.2.0
        id: checkTag
        with:
          tag: "${{ steps.versions.outputs.CURRENT_VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify tag is documented
        run: |
          if ${{ steps.checkTag.outputs.exists }}; then
            echo "========================================================================"
            echo "Error: ${{ steps.versions.outputs.CURRENT_VERSION }} exists";
            echo "========================================================================"
            exit 1;
          else
            echo "${{ steps.versions.outputs.CURRENT_VERSION }} does not exist"
          fi      


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Get Current Timestamp
        if: success()
        id: date
        run: echo "NOW=$(date +'%Y-%m-%d-%H-%M')">> $GITHUB_OUTPUT

      - name: Get versioning information
        id: versions
        run: |
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          CURRENT_VERSION=$(cat seqslab/__init__.py | grep "__version__"| awk '{print $3}' | sed 's/^"//'| sed 's/"$//' )
          
          # set output
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Print versioning information
        run: |
          
          # set output
          echo "Print Datetime"
          echo ${{ steps.date.outputs.NOW }}
          echo "Print CURRENT_VERSION"
          echo ${{ steps.versions.outputs.CURRENT_VERSION }}

      # Publish pre Release
      - name: Create Seqslab Connector Draft Release
        if: (github.ref == 'refs/heads/main') && (github.event.inputs.draftRelease == 'Yes') && success()
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.versions.outputs.CURRENT_VERSION }}
          release_name: ${{ steps.versions.outputs.CURRENT_VERSION }}
          body: |
            TimeStamp
            - timestamp = ${{ steps.date.outputs.NOW }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
